START TRANSACTION;


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Datenbank: guidedlands
--

-- --------------------------------------------------------

ALTER TABLE race ADD weight_11 INT NOT NULL AFTER data_initiativevalue_initiative;
ALTER TABLE race ADD weight_10 INT NOT NULL AFTER weight_11;
ALTER TABLE race ADD weight_9 INT NOT NULL AFTER weight_10;
ALTER TABLE race ADD weight_8 INT NOT NULL AFTER weight_9;
ALTER TABLE race ADD weight_7 INT NOT NULL AFTER weight_8;
ALTER TABLE race ADD weight_6 INT NOT NULL AFTER weight_7;
ALTER TABLE race ADD weight_5 INT NOT NULL AFTER weight_6;
ALTER TABLE race ADD weight_4 INT NOT NULL AFTER weight_5;
ALTER TABLE race ADD weight_3 INT NOT NULL AFTER weight_4;
ALTER TABLE race ADD weight_2 INT NOT NULL AFTER weight_3;
ALTER TABLE race ADD weight_1 INT NOT NULL AFTER weight_2;

COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
