START TRANSACTION;


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Datenbank: `guidedlands`
--

-- --------------------------------------------------------


ALTER TABLE figuresize ADD UNIQUE(text);
ALTER TABLE figuresizevalue ADD PRIMARY KEY(figuresize_id);
ALTER TABLE deathvalue ADD UNIQUE(death);
ALTER TABLE injuryvalue ADD UNIQUE(injury);
ALTER TABLE lifevalue ADD UNIQUE(life);
ALTER TABLE initiativevalue ADD UNIQUE(initiative);

COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
