# This is a basic workflow that is manually triggered

name: Build and deploy develop

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
 push:
  branches:
    - develop
 pull_request:
   branches:
    - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  database:
    environment: develop
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: joshuaavalon/flyway-action@v2.1.0
      with:
        # The jdbc url to use to connect to the database
        url: $***REMOVED******REMOVED*** secrets.DB ***REMOVED******REMOVED***
        # The user to use to connect to the database
        user: $***REMOVED******REMOVED*** secrets.DBUSER ***REMOVED******REMOVED***
        # The password to use to connect to the database
        password: $***REMOVED******REMOVED*** secrets.DBPW ***REMOVED******REMOVED***
        # Comma-separated list of locations to scan recursively for migrations
        # locations: ./sql
  build:
    environment: develop
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: '6.0.x'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore dependencies
        run: dotnet restore GuidedLands.sln
      - name: Build
        run: dotnet build GuidedLands.sln
