# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
 push:
  branches:
    - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  database:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Flyway Migration
      # You may pin to the exact commit or the version.
      # uses: joshuaavalon/flyway-action@c3064cb4f96e4bb3a6acae6d6ab995b83c41c54d
      uses: joshuaavalon/flyway-action@v2.1.0
      with:
        # The jdbc url to use to connect to the database
        url: ${{ secrets.DB }}
        # The user to use to connect to the database
        user: ${{ secrets.DBUSER }}
        # The password to use to connect to the database
        password: ${{ secrets.DBPW }}
        # Comma-separated list of locations to scan recursively for migrations
        locations: ./sql
